name = "study-with-miku-onlinecounter"
main = "workers/online-counter.js"
compatibility_date = "2023-10-01"

[[durable_objects.bindings]]
name = "ONLINE_COUNTER"
class_name = "OnlineCounter"

[[migrations]]
tag = "v1"
new_classes = ["OnlineCounter"]
